export type DiagnosticSeverity = "blocker" | "warning" | "info";
export type DiagnosticCategory = "release_proof" | "model_source" | "runtime_backend" | "workflow_ui";
export type ProofImpact = "blocks_beta" | "blocks_ai_proof" | "blocks_workflow" | "none";

export interface DiagnosticDefinition {
  code: string;
  severity: DiagnosticSeverity;
  category: DiagnosticCategory;
  userMessage: string;
  developerMessage: string;
  suggestedFix: string;
  proofImpact: ProofImpact;
  canUserFix: boolean;
  canDeveloperFix: boolean;
  expectedBlocker: boolean;
}

export const DIAGNOSTIC_CODES = {
  PROOF_MODEL_MISSING: {
    code: "PROOF_MODEL_MISSING",
    severity: "blocker",
    category: "release_proof",
    userMessage: "No verified model file is available for AI proof.",
    developerMessage: "CPU AI proof cannot run until a selected model exists locally and passes integrity checks.",
    suggestedFix: "Import or reconnect a model with verified metadata and a matching SHA-256.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: false,
    expectedBlocker: true,
  },
  PROOF_MODEL_HASH_MISMATCH: {
    code: "PROOF_MODEL_HASH_MISMATCH",
    severity: "blocker",
    category: "release_proof",
    userMessage: "The selected model hash does not match expected proof metadata.",
    developerMessage: "Hash mismatch must block proof and release claims.",
    suggestedFix: "Use the correct verified model file or repair metadata with a legitimate expected SHA-256.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  PROOF_MODEL_HASH_MISSING: {
    code: "PROOF_MODEL_HASH_MISSING",
    severity: "blocker",
    category: "release_proof",
    userMessage: "Expected SHA-256 metadata is missing for the selected model.",
    developerMessage: "Proof cannot run when expected model integrity metadata is absent.",
    suggestedFix: "Provide verified metadata with a 64-hex SHA-256 and usable license.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  PROOF_MODEL_MANIFEST_INVALID: {
    code: "PROOF_MODEL_MANIFEST_INVALID",
    severity: "blocker",
    category: "release_proof",
    userMessage: "Proof model manifest is incomplete or invalid.",
    developerMessage: "The local proof manifest is missing required metadata for strict CPU E2E proof.",
    suggestedFix:
      "Fill the local manifest with verified filename, source/license, SHA-256, size, backend, and expected stems.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  PROOF_MODEL_FILENAME_MISMATCH: {
    code: "PROOF_MODEL_FILENAME_MISMATCH",
    severity: "blocker",
    category: "release_proof",
    userMessage: "Proof model filename does not match the manifest.",
    developerMessage: "Filename mismatch may indicate the wrong local asset even before hash checks.",
    suggestedFix: "Reconnect the exact model file named in the verified proof manifest.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  PROOF_MODEL_SIZE_MISMATCH: {
    code: "PROOF_MODEL_SIZE_MISMATCH",
    severity: "blocker",
    category: "release_proof",
    userMessage: "Proof model size does not match the manifest.",
    developerMessage: "Size mismatch blocks proof even if a filename appears plausible.",
    suggestedFix: "Use the verified model file whose size and SHA-256 match the manifest.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  PROOF_BACKEND_MISSING: {
    code: "PROOF_BACKEND_MISSING",
    severity: "blocker",
    category: "release_proof",
    userMessage: "The local AI backend is missing required runtime pieces.",
    developerMessage: "Python, audio-separator, PyTorch, or CLI inspection failed.",
    suggestedFix: "Run backend diagnostics and install the missing runtime dependency.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  PROOF_INPUT_MISSING: {
    code: "PROOF_INPUT_MISSING",
    severity: "blocker",
    category: "release_proof",
    userMessage: "No verified input audio file is available for proof.",
    developerMessage: "Proof requires a real local input path.",
    suggestedFix: "Select a real local audio input through Electron.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: false,
    expectedBlocker: true,
  },
  PROOF_INPUT_GENERATION_FAILED: {
    code: "PROOF_INPUT_GENERATION_FAILED",
    severity: "blocker",
    category: "release_proof",
    userMessage: "Synthetic proof input could not be generated.",
    developerMessage: "FFmpeg failed to create the copyright-safe proof input WAV.",
    suggestedFix: "Verify FFmpeg, rerun proof input generation, and inspect the command output.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  PROOF_INPUT_UNDECODABLE: {
    code: "PROOF_INPUT_UNDECODABLE",
    severity: "blocker",
    category: "release_proof",
    userMessage: "Proof input audio is not decodable.",
    developerMessage: "FFprobe could not read an audio stream from the proof input.",
    suggestedFix: "Regenerate the synthetic proof input or select a decodable local WAV.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  PROOF_OUTPUT_MISSING: {
    code: "PROOF_OUTPUT_MISSING",
    severity: "blocker",
    category: "release_proof",
    userMessage: "No verified writable output folder is available.",
    developerMessage: "Proof requires a real writable output directory.",
    suggestedFix: "Select an existing writable output folder.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: false,
    expectedBlocker: true,
  },
  PROOF_OUTPUT_EMPTY: {
    code: "PROOF_OUTPUT_EMPTY",
    severity: "blocker",
    category: "release_proof",
    userMessage: "The backend did not produce non-empty AI output stems.",
    developerMessage: "Exit code or output verification failed the AI proof contract.",
    suggestedFix: "Inspect backend logs, model compatibility, and output paths.",
    proofImpact: "blocks_ai_proof",
    canUserFix: false,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  PROOF_OUTPUT_STALE: {
    code: "PROOF_OUTPUT_STALE",
    severity: "blocker",
    category: "release_proof",
    userMessage: "No new output stems were created by the proof run.",
    developerMessage: "Stale files from an older run must not satisfy CPU AI proof.",
    suggestedFix: "Use an isolated proof output folder and rerun the verified backend command.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  PROOF_OUTPUT_UNDECODABLE: {
    code: "PROOF_OUTPUT_UNDECODABLE",
    severity: "blocker",
    category: "release_proof",
    userMessage: "A proof output stem is not decodable audio.",
    developerMessage: "Output files must be non-empty and decodable before proof can pass.",
    suggestedFix: "Inspect backend logs, model compatibility, FFmpeg/ffprobe, and output paths.",
    proofImpact: "blocks_ai_proof",
    canUserFix: false,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  PROOF_SEPARATION_FAILED: {
    code: "PROOF_SEPARATION_FAILED",
    severity: "blocker",
    category: "release_proof",
    userMessage: "Local AI separation failed.",
    developerMessage: "The audio-separator subprocess failed before proof outputs were verified.",
    suggestedFix: "Inspect stderr/stdout, model compatibility, Python runtime, and audio-separator CLI arguments.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  PROOF_E2E_NOT_RUN: {
    code: "PROOF_E2E_NOT_RUN",
    severity: "blocker",
    category: "release_proof",
    userMessage: "The verified local AI E2E proof has not been run yet.",
    developerMessage: "Model/backend/input readiness is complete, but no durable passing proof report was found.",
    suggestedFix: "Run the suggested test-ai-e2e.cjs command and rerun proof:check.",
    proofImpact: "blocks_beta",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  PROOF_FFMPEG_FALLBACK_NON_AI: {
    code: "PROOF_FFMPEG_FALLBACK_NON_AI",
    severity: "blocker",
    category: "release_proof",
    userMessage: "FFmpeg fallback is non-AI and cannot satisfy AI proof.",
    developerMessage: "Non-neural fallback output must not count as stem-separation proof.",
    suggestedFix: "Run a verified neural AI separation path for proof.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: false,
    expectedBlocker: true,
  },
  PROOF_BETA_BLOCKED: {
    code: "PROOF_BETA_BLOCKED",
    severity: "blocker",
    category: "release_proof",
    userMessage: "Beta Candidate is not approved yet.",
    developerMessage:
      "Release tooling and one local proof lane are evidence, but Beta still requires final release checklist review and user approval.",
    suggestedFix: "Complete final release review and confirm durable local proof evidence before approving Beta Candidate.",
    proofImpact: "blocks_beta",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  MODEL_SOURCE_AUTH_REQUIRED: {
    code: "MODEL_SOURCE_AUTH_REQUIRED",
    severity: "blocker",
    category: "model_source",
    userMessage: "Model source requires authorization.",
    developerMessage: "HTTP 401 means the server was reached but access is unavailable.",
    suggestedFix: "Use legitimate authentication or corrected source metadata, then verify SHA-256.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  MODEL_SOURCE_ACCESS_DENIED: {
    code: "MODEL_SOURCE_ACCESS_DENIED",
    severity: "blocker",
    category: "model_source",
    userMessage: "Model source access is denied or gated.",
    developerMessage: "HTTP 403 blocks download and proof until legitimate access exists.",
    suggestedFix: "Use an authorized source and matching SHA-256 metadata.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  MODEL_SOURCE_BROKEN_LINK: {
    code: "MODEL_SOURCE_BROKEN_LINK",
    severity: "blocker",
    category: "model_source",
    userMessage: "Model source link is missing or stale.",
    developerMessage: "HTTP 404 requires source metadata repair; do not treat it as auth or no internet.",
    suggestedFix:
      "Repair metadata only with a legitimate source, usable license, expected SHA-256, and local hash match.",
    proofImpact: "blocks_ai_proof",
    canUserFix: false,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  MODEL_SOURCE_UNAVAILABLE: {
    code: "MODEL_SOURCE_UNAVAILABLE",
    severity: "blocker",
    category: "model_source",
    userMessage: "Model source is unavailable or could not be checked.",
    developerMessage: "Network, DNS, timeout, or server failure prevented a trusted source check.",
    suggestedFix: "Retry diagnostics and keep model proof blocked until source integrity is verified.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  MODEL_SOURCE_RATE_LIMITED: {
    code: "MODEL_SOURCE_RATE_LIMITED",
    severity: "warning",
    category: "model_source",
    userMessage: "Model source is rate-limited.",
    developerMessage: "HTTP 429 prevents source verification in this check.",
    suggestedFix: "Retry later and do not mark the model verified from a rate-limited check.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: false,
    expectedBlocker: true,
  },
  MODEL_METADATA_MISSING_HASH: {
    code: "MODEL_METADATA_MISSING_HASH",
    severity: "blocker",
    category: "model_source",
    userMessage: "Model metadata is missing expected SHA-256.",
    developerMessage: "Missing checksum prevents source integrity and proof eligibility.",
    suggestedFix: "Provide expected SHA-256 from verified source metadata.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  MODEL_METADATA_MISSING_LICENSE: {
    code: "MODEL_METADATA_MISSING_LICENSE",
    severity: "blocker",
    category: "model_source",
    userMessage: "Model license metadata is missing.",
    developerMessage: "Proof eligibility requires usable source and license metadata.",
    suggestedFix: "Document a usable license before proof or release claims.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  MODEL_LOCAL_FILE_MISSING: {
    code: "MODEL_LOCAL_FILE_MISSING",
    severity: "blocker",
    category: "model_source",
    userMessage: "Local model file is missing.",
    developerMessage: "The selected model path does not resolve to a verified local file.",
    suggestedFix: "Download, import, or reconnect the correct local model file.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: false,
    expectedBlocker: true,
  },
  MODEL_LOCAL_HASH_MISMATCH: {
    code: "MODEL_LOCAL_HASH_MISMATCH",
    severity: "blocker",
    category: "model_source",
    userMessage: "Local model SHA-256 does not match expected metadata.",
    developerMessage: "Hash mismatch must block model use, proof, and release claims.",
    suggestedFix: "Replace the local file with the verified asset or correct metadata with proof.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  MODEL_MANUAL_IMPORT_REQUIRED: {
    code: "MODEL_MANUAL_IMPORT_REQUIRED",
    severity: "blocker",
    category: "model_source",
    userMessage: "Manual import requires verified metadata before proof.",
    developerMessage: "Manual imports without expected SHA-256 cannot become proof-eligible.",
    suggestedFix: "Import strict metadata and reconnect a local file with matching SHA-256.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  RUNTIME_BROWSER_PREVIEW_ONLY: {
    code: "RUNTIME_BROWSER_PREVIEW_ONLY",
    severity: "blocker",
    category: "runtime_backend",
    userMessage: "Browser preview cannot run native audio workflows.",
    developerMessage: "Native filesystem/backend IPC is unavailable outside Electron.",
    suggestedFix: "Run the Electron desktop app for native downloads, verification, and processing.",
    proofImpact: "blocks_workflow",
    canUserFix: true,
    canDeveloperFix: false,
    expectedBlocker: true,
  },
  RUNTIME_NATIVE_BACKEND_REQUIRED: {
    code: "RUNTIME_NATIVE_BACKEND_REQUIRED",
    severity: "blocker",
    category: "runtime_backend",
    userMessage: "Native Electron backend is required for this action.",
    developerMessage: "The requested operation needs a preload IPC method and native main-process handler.",
    suggestedFix: "Use the desktop app or implement the missing native bridge contract.",
    proofImpact: "blocks_workflow",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  RUNTIME_PYTHON_MISSING: {
    code: "RUNTIME_PYTHON_MISSING",
    severity: "blocker",
    category: "runtime_backend",
    userMessage: "Python runtime is missing.",
    developerMessage: "AI backend diagnostics could not find a usable Python executable.",
    suggestedFix: "Configure Python 3.10+ or the documented project-local environment.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: false,
    expectedBlocker: true,
  },
  RUNTIME_AUDIO_SEPARATOR_MISSING: {
    code: "RUNTIME_AUDIO_SEPARATOR_MISSING",
    severity: "blocker",
    category: "runtime_backend",
    userMessage: "audio-separator is missing.",
    developerMessage: "The selected Python environment cannot import or inspect audio-separator.",
    suggestedFix: "Install or repair audio-separator in the selected Python environment.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  RUNTIME_PYTORCH_MISSING: {
    code: "RUNTIME_PYTORCH_MISSING",
    severity: "blocker",
    category: "runtime_backend",
    userMessage: "PyTorch runtime is missing.",
    developerMessage: "The selected Python environment cannot import torch.",
    suggestedFix: "Install a compatible PyTorch build for the intended device.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  RUNTIME_FFMPEG_MISSING: {
    code: "RUNTIME_FFMPEG_MISSING",
    severity: "blocker",
    category: "runtime_backend",
    userMessage: "FFmpeg is missing.",
    developerMessage: "FFmpeg detection failed or ffmpeg -version did not run successfully.",
    suggestedFix: "Install FFmpeg or configure PATH so the native process can find it.",
    proofImpact: "blocks_ai_proof",
    canUserFix: true,
    canDeveloperFix: false,
    expectedBlocker: true,
  },
  RUNTIME_DEVICE_NOT_PROVEN: {
    code: "RUNTIME_DEVICE_NOT_PROVEN",
    severity: "warning",
    category: "runtime_backend",
    userMessage: "Selected hardware device is not locally proven.",
    developerMessage: "CUDA, MPS, or DirectML requires separate local E2E proof.",
    suggestedFix: "Use CPU for the current proof path or run documented device proof later.",
    proofImpact: "none",
    canUserFix: true,
    canDeveloperFix: false,
    expectedBlocker: true,
  },
  RUNTIME_PACKAGED_RESOURCE_MISSING: {
    code: "RUNTIME_PACKAGED_RESOURCE_MISSING",
    severity: "blocker",
    category: "runtime_backend",
    userMessage: "Packaged runtime resource is missing.",
    developerMessage: "Electron package verification found a missing required resource.",
    suggestedFix: "Fix electron-builder resources and rerun artifact verification.",
    proofImpact: "blocks_workflow",
    canUserFix: false,
    canDeveloperFix: true,
    expectedBlocker: false,
  },
  MIXER_NO_VERIFIED_SESSION: {
    code: "MIXER_NO_VERIFIED_SESSION",
    severity: "blocker",
    category: "workflow_ui",
    userMessage: "No verified stem session loaded.",
    developerMessage: "Mixer playback/export requires verified real stems from a local separation job.",
    suggestedFix: "Run a verified local separation job before mixer playback or export.",
    proofImpact: "blocks_workflow",
    canUserFix: true,
    canDeveloperFix: false,
    expectedBlocker: true,
  },
  MIXER_EXPORT_BACKEND_MISSING: {
    code: "MIXER_EXPORT_BACKEND_MISSING",
    severity: "blocker",
    category: "workflow_ui",
    userMessage: "Mixer export backend is not implemented.",
    developerMessage: "Mixdown exporter controls are disabled until native export wiring exists.",
    suggestedFix: "Implement export backend before enabling mixdown output.",
    proofImpact: "blocks_workflow",
    canUserFix: false,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  MIXER_STEM_FILES_MISSING: {
    code: "MIXER_STEM_FILES_MISSING",
    severity: "blocker",
    category: "workflow_ui",
    userMessage: "One or more stem files are missing or unverified.",
    developerMessage: "Mixer cannot export demo, placeholder, or missing stem files.",
    suggestedFix: "Load verified output stems from a real local separation run.",
    proofImpact: "blocks_workflow",
    canUserFix: true,
    canDeveloperFix: false,
    expectedBlocker: true,
  },
  ENSEMBLE_BACKEND_NOT_IMPLEMENTED: {
    code: "ENSEMBLE_BACKEND_NOT_IMPLEMENTED",
    severity: "blocker",
    category: "workflow_ui",
    userMessage: "Ensemble execution backend is not implemented.",
    developerMessage: "The ensemble panel is a planner only and cannot run aggregation.",
    suggestedFix: "Implement backend runner and verification before enabling execution.",
    proofImpact: "blocks_workflow",
    canUserFix: false,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  ENSEMBLE_PLANNER_ONLY: {
    code: "ENSEMBLE_PLANNER_ONLY",
    severity: "info",
    category: "workflow_ui",
    userMessage: "Ensemble view is a planner only.",
    developerMessage: "Planner state must not claim output files or AI proof.",
    suggestedFix: "Keep planner wording until backend execution is implemented.",
    proofImpact: "none",
    canUserFix: false,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  BATCH_QUEUE_EMPTY: {
    code: "BATCH_QUEUE_EMPTY",
    severity: "blocker",
    category: "workflow_ui",
    userMessage: "Batch queue is empty.",
    developerMessage: "Batch encoding requires at least one queued input file.",
    suggestedFix: "Add audio files to the batch queue.",
    proofImpact: "none",
    canUserFix: true,
    canDeveloperFix: false,
    expectedBlocker: true,
  },
  BATCH_OUTPUT_FOLDER_MISSING: {
    code: "BATCH_OUTPUT_FOLDER_MISSING",
    severity: "blocker",
    category: "workflow_ui",
    userMessage: "Batch output folder is missing.",
    developerMessage: "Batch encoding requires an output target path.",
    suggestedFix: "Choose an output directory before running batch conversion.",
    proofImpact: "none",
    canUserFix: true,
    canDeveloperFix: false,
    expectedBlocker: true,
  },
  BASIC_PITCH_DRY_RUN_ONLY: {
    code: "BASIC_PITCH_DRY_RUN_ONLY",
    severity: "warning",
    category: "workflow_ui",
    userMessage: "Basic Pitch is running as browser dry-run only.",
    developerMessage: "Browser preview cannot write local MIDI, WAV, CSV, or NPZ files.",
    suggestedFix: "Run in Electron with Basic Pitch backend configured for real local output.",
    proofImpact: "none",
    canUserFix: true,
    canDeveloperFix: false,
    expectedBlocker: true,
  },
  GENERATIVE_CONNECTOR_NOT_CONFIGURED: {
    code: "GENERATIVE_CONNECTOR_NOT_CONFIGURED",
    severity: "blocker",
    category: "workflow_ui",
    userMessage: "Generative connector is not configured.",
    developerMessage: "Generation requires a supported user-authorized connector, not raw cookies or bypass flows.",
    suggestedFix: "Configure a supported connector or use text-only drafting tools.",
    proofImpact: "none",
    canUserFix: true,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
  YUE_LOCAL_ENGINE_NOT_WIRED: {
    code: "YUE_LOCAL_ENGINE_NOT_WIRED",
    severity: "blocker",
    category: "workflow_ui",
    userMessage: "YuE local engine is not wired with local weights.",
    developerMessage: "YuE generation requires local weights, backend wiring, preflight, and user acknowledgement.",
    suggestedFix: "Wire the local YuE backend and verify weights before enabling local generation.",
    proofImpact: "none",
    canUserFix: false,
    canDeveloperFix: true,
    expectedBlocker: true,
  },
} as const satisfies Record<string, DiagnosticDefinition>;

export type DiagnosticCode = keyof typeof DIAGNOSTIC_CODES;

export const SOURCE_STATUS_DIAGNOSTIC_CODES: Record<string, DiagnosticCode> = {
  auth_required: "MODEL_SOURCE_AUTH_REQUIRED",
  gated_or_private: "MODEL_SOURCE_ACCESS_DENIED",
  access_denied: "MODEL_SOURCE_ACCESS_DENIED",
  broken_link: "MODEL_SOURCE_BROKEN_LINK",
  rate_limited: "MODEL_SOURCE_RATE_LIMITED",
  source_unavailable: "MODEL_SOURCE_UNAVAILABLE",
  network_unavailable: "MODEL_SOURCE_UNAVAILABLE",
  dns_failed: "MODEL_SOURCE_UNAVAILABLE",
  timeout: "MODEL_SOURCE_UNAVAILABLE",
  unavailable: "MODEL_SOURCE_UNAVAILABLE",
  missing_hash: "MODEL_METADATA_MISSING_HASH",
  hash_mismatch: "MODEL_LOCAL_HASH_MISMATCH",
  needs_verification: "MODEL_MANUAL_IMPORT_REQUIRED",
  custom_unverified: "MODEL_MANUAL_IMPORT_REQUIRED",
  custom_hash_unavailable: "MODEL_METADATA_MISSING_HASH",
  verified_local: "MODEL_SOURCE_UNAVAILABLE",
};

export const PROOF_REASON_DIAGNOSTIC_CODES: Record<string, DiagnosticCode> = {
  missing_file: "PROOF_MODEL_MISSING",
  hash_mismatch: "MODEL_LOCAL_HASH_MISMATCH",
  size_mismatch: "MODEL_LOCAL_HASH_MISMATCH",
  hash_missing: "PROOF_MODEL_HASH_MISSING",
  manifest_invalid: "PROOF_MODEL_MANIFEST_INVALID",
  filename_mismatch: "PROOF_MODEL_FILENAME_MISMATCH",
  output_stale: "PROOF_OUTPUT_STALE",
  output_undecodable: "PROOF_OUTPUT_UNDECODABLE",
  missing_hash: "MODEL_METADATA_MISSING_HASH",
  custom_unverified: "MODEL_MANUAL_IMPORT_REQUIRED",
  custom_hash_unavailable: "MODEL_METADATA_MISSING_HASH",
  source_missing: "MODEL_SOURCE_UNAVAILABLE",
  auth_required: "MODEL_SOURCE_AUTH_REQUIRED",
  gated_or_private: "MODEL_SOURCE_ACCESS_DENIED",
  access_denied: "MODEL_SOURCE_ACCESS_DENIED",
  rate_limited: "MODEL_SOURCE_RATE_LIMITED",
  source_unavailable: "MODEL_SOURCE_UNAVAILABLE",
  network_unavailable: "MODEL_SOURCE_UNAVAILABLE",
  dns_failed: "MODEL_SOURCE_UNAVAILABLE",
  timeout: "MODEL_SOURCE_UNAVAILABLE",
  unavailable: "MODEL_SOURCE_UNAVAILABLE",
  broken_link: "MODEL_SOURCE_BROKEN_LINK",
  unsupported_backend: "PROOF_BACKEND_MISSING",
  license_missing: "MODEL_METADATA_MISSING_LICENSE",
  manual_import_required: "MODEL_MANUAL_IMPORT_REQUIRED",
};

export const LEGACY_BLOCKER_DIAGNOSTIC_CODES: Record<string, DiagnosticCode> = {
  browser_preview_mode: "RUNTIME_BROWSER_PREVIEW_ONLY",
  browser_sandbox: "RUNTIME_BROWSER_PREVIEW_ONLY",
  browser_mode: "RUNTIME_BROWSER_PREVIEW_ONLY",
  no_inputs: "PROOF_INPUT_MISSING",
  inputs_not_verified: "PROOF_INPUT_MISSING",
  input_missing: "PROOF_INPUT_MISSING",
  same_as_input_requires_native: "RUNTIME_NATIVE_BACKEND_REQUIRED",
  output_missing: "PROOF_OUTPUT_MISSING",
  output_not_exists: "PROOF_OUTPUT_MISSING",
  output_not_writable: "PROOF_OUTPUT_MISSING",
  output_stale: "PROOF_OUTPUT_STALE",
  output_undecodable: "PROOF_OUTPUT_UNDECODABLE",
  output_browser_preview: "RUNTIME_BROWSER_PREVIEW_ONLY",
  model_missing: "PROOF_MODEL_MISSING",
  model_not_installed: "MODEL_LOCAL_FILE_MISSING",
  model_hash_mismatch: "MODEL_LOCAL_HASH_MISMATCH",
  model_hash_missing: "PROOF_MODEL_HASH_MISSING",
  model_manifest_invalid: "PROOF_MODEL_MANIFEST_INVALID",
  model_filename_mismatch: "PROOF_MODEL_FILENAME_MISMATCH",
  model_size_mismatch: "PROOF_MODEL_SIZE_MISMATCH",
  model_proof_not_eligible: "PROOF_MODEL_HASH_MISSING",
  model_manual_import_required: "MODEL_MANUAL_IMPORT_REQUIRED",
  model_auth_required: "MODEL_SOURCE_AUTH_REQUIRED",
  model_access_denied: "MODEL_SOURCE_ACCESS_DENIED",
  model_broken_link: "MODEL_SOURCE_BROKEN_LINK",
  model_source_unavailable: "MODEL_SOURCE_UNAVAILABLE",
  unsupported_architecture: "PROOF_BACKEND_MISSING",
  ffmpeg_missing: "RUNTIME_FFMPEG_MISSING",
  ffprobe_missing: "RUNTIME_FFMPEG_MISSING",
  python_missing: "RUNTIME_PYTHON_MISSING",
  audio_separator_missing: "RUNTIME_AUDIO_SEPARATOR_MISSING",
  audio_separator_cli_missing: "RUNTIME_AUDIO_SEPARATOR_MISSING",
  torch_missing: "RUNTIME_PYTORCH_MISSING",
  cpu_mode_required: "RUNTIME_DEVICE_NOT_PROVEN",
  cuda_missing: "RUNTIME_DEVICE_NOT_PROVEN",
  mps_missing: "RUNTIME_DEVICE_NOT_PROVEN",
  cuda_not_proven: "RUNTIME_DEVICE_NOT_PROVEN",
  directml_experimental: "RUNTIME_DEVICE_NOT_PROVEN",
  ffmpeg_fallback_blocked: "PROOF_FFMPEG_FALLBACK_NON_AI",
  non_ai_mode: "PROOF_FFMPEG_FALLBACK_NON_AI",
  ensemble_insufficient_inputs: "ENSEMBLE_PLANNER_ONLY",
};

export function getDiagnostic(code: DiagnosticCode): DiagnosticDefinition {
  return DIAGNOSTIC_CODES[code];
}

export function getDiagnosticCodeForSourceStatus(status?: string): DiagnosticCode {
  return (status && SOURCE_STATUS_DIAGNOSTIC_CODES[status]) || "MODEL_SOURCE_UNAVAILABLE";
}

export function getDiagnosticCodeForProofReason(reason?: string): DiagnosticCode {
  return (reason && PROOF_REASON_DIAGNOSTIC_CODES[reason]) || "PROOF_MODEL_MISSING";
}

export function getDiagnosticCodeForLegacyBlocker(id?: string): DiagnosticCode {
  return (id && LEGACY_BLOCKER_DIAGNOSTIC_CODES[id]) || "RUNTIME_NATIVE_BACKEND_REQUIRED";
}

export function formatDiagnosticCode(code: DiagnosticCode | string): string {
  return `Code: ${code}`;
}
